---
  - name: install slurm dependences in Deb systems
    apt: name=libmunge2,libpq5,openssl-blacklist,munge,libmunge-dev,gcc,make,bzip2 update_cache=yes cache_valid_time=3600

  - name: download SLURM package
    get_url: url=http://www.schedmd.com/download/archive/slurm-{{ slurm_version }}.tar.bz2 dest=/tmp/slurm.tar.bz2

  - name: decompress SLURM package
    command: tar xjf slurm.tar.bz2 chdir=/tmp creates=/tmp/slurm-{{ slurm_version }}

  - name: configure SLURM
    command: ./configure {{ "--with-blcr=/usr/local/bin" if "blcr" in templates else "" }} chdir=/tmp/slurm-{{ slurm_version }} creates=/tmp/slurm-{{ slurm_version }}/config.log

  - name: compile (make) SLURM
    command: make chdir=/tmp/slurm-{{ slurm_version }} creates=/tmp/slurm-{{ slurm_version }}/src/slurmctld

  - name: install SLURM
    command: make install chdir=/tmp/slurm-{{ slurm_version }} creates=/usr/local/bin/srun

  - name: Set SLURM conf file path as fact
    set_fact:
      SLURM_CONF: "/usr/local/etc/slurm.conf"
      SLURM_SERVICE: "slurmctld"
      SLURM_DAEMON: "slurmd"
