---
  - name: update repositories cache and apt install slurm dependences in Deb systems
    apt: name=libmunge2,libpq5,openssl-blacklist,munge,libmunge-dev,gcc,make  update_cache=yes cache_valid_time=3600

  - name: download SLURM package
    get_url: url=http://www.schedmd.com/download/archive/slurm-14.11.3.tar.bz2 dest=/tmp/slurm.tar.bz2

  - name: decompress SLURM package
    command: tar xjf slurm.tar.bz2 chdir=/tmp creates=/tmp/slurm-14.11.3

#  - name: configure SLURM
#    command: ./configure {{ "--with-blcr=/usr/local/bin" if "blcr" in TEMPLATES else "" }} chdir=/tmp/slurm-14.11.3 creates=/tmp/slurm-14.11.3/config.log

  - name: compile (make) SLURM
    command: make chdir=/tmp/slurm-14.11.3 creates=/tmp/slurm-14.11.3/src/slurmctld

  - name: install SLURM
    command: make install chdir=/tmp/slurm-14.11.3 creates=/usr/local/bin/srun

  - name: create slurm user and group
    user: name=slurm shell=/bin/bash system=yes

  - name: create folders used by SLURM and set slurm owner
    file: path={{item}} state=directory owner=slurm group=slurm
    with_items:
       - /var/spool/slurm
       - /var/log/slurm
       - /var/slurm/checkpoint
       - /etc/slurm
