---
  - name: Create the slurm.conf file
    template: dest={{ SLURM_CONF }} src=slurm.conf.j2
    notify: reload slurm

  - name: Start SLURM daemon
    service: name={{SLURM_SERVICE}} state=started

  - name: Ensure slurmd is not running in front node
    shell: pgrep slurmd && killall slurmd
    ignore_errors: yes
