---
  - name: Copy 'is_cluster_ready' file
    copy: dest=/bin/is_cluster_ready src=is_cluster_ready mode=0755

    # Manage the /etc/hosts file
  - shell: |
      for i in `seq 1 {{item.ec3_max_instances_max|int }}`; do
        item="{{item.id|replace('_','x')}}${i}";
        grep -q "\<${item}\>" /etc/hosts || echo "127.0.0.1 ${item} ${item}.localdomain" >> /etc/hosts;
      done
    with_items: '{{ SYSTEMS | selectattr("ec3_max_instances_max", "defined") | list }}'

  - name: Create the slurm.conf file
    template: dest={{ SLURM_CONF }} src=slurm.conf.j2

  - name: Set blcr config in SLURM
    lineinfile: dest={{ SLURM_CONF }} regexp='#CheckpointType=' line='CheckpointType=checkpoint/blcr' state=present
    when: "'blcr' in templates"

  - name: configure compute nodes section of slurm.conf
    lineinfile: dest=/usr/local/etc/slurm.conf regexp='NodeName={{item.id|replace('_','x')}}\[' line='NodeName={{item.id|replace('_','x')}}[1-{{item.ec3_max_instances_max|int}}] CPUs=1 State=UNKNOWN' state=present
    with_items: '{{ SYSTEMS | selectattr("ec3_max_instances_max", "defined") | list }}'

  - lineinfile: dest=/usr/local/etc/slurm.conf regexp='PartitionName={{item.id}} ' line='PartitionName={{item.id}} Nodes={{item.id|replace('_','x')}}[1-{{item.ec3_max_instances_max|int}}] MaxTime=INFINITE State=UP' state=present
    with_items: '{{ SYSTEMS | selectattr("ec3_max_instances_max", "defined") | list }}'

  - name: Start SLURM service
    become: true
    become_user: slurm
    command: slurmctld

  - name: Ensure slurmd is not running in front node
    shell: pgrep slurmd && killall slurmd
    ignore_errors: yes

  - name: Reconfigure SLURM
    become: true
    become_user: slurm
    command: scontrol reconfigure
