---
    # configure munge
    - shell: create-munge-key < /dev/null creates=/etc/munge/munge.key
      when: not munge_key.stat.exists
      notify: restart munge

    - service: name=munge state=started

    - name: Create the slurm.conf file
      template: dest={{ SLURM_CONF }} src=slurm.conf.j2
      notify: reload slurm

    # start SLURM daemon
    - service: name={{SLURM_SERVICE}} state=started
    
    - name: Ensure slurmd is not running in front node
      shell: pgrep slurmd && killall slurmd
      ignore_errors: yes
