---
  - name: Include "{{ansible_os_family}}" SLURM recipe
    include: "{{ansible_os_family}}.yaml"

  - name: Include "{{slurm_type_of_node}}" SLURM recipe
    include: "{{slurm_type_of_node}}.yaml"
