---
  - name: Include "{{ansible_os_family}}" SLURM recipe
    include: "{{ansible_os_family}}.yaml"

  - name: create slurm user and group
    user: name="{{slurm_user}}" shell=/bin/bash system=yes

  - name: create folders used by SLURM and set slurm owner
    file: path={{item}} state=directory owner=slurm group=slurm
    with_items:
      - /var/spool/slurm
      - /var/log/slurm
      - /var/slurm/checkpoint
      - /etc/slurm

  - name: Include "{{slurm_type_of_node}}" SLURM recipe
    include: "{{slurm_type_of_node}}.yaml"
