---
  #SLURM dependences
  - name: Install epel repo
    yum: name=epel-release

  - name: Set Centos 6 facts
    set_fact:
      SLURM_VERSION: "16.05.05-1.el6"
      PKG_FOLDER: "centos6/16.05.5"
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6

  - name: Set Centos 7 facts
    set_fact:
      SLURM_VERSION: "16.05.05-1.el7.centos"
      PKG_FOLDER: "centos7/16.05.5"
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7

  - name: Copy required packages
    copy: src={{PKG_FOLDER}}/{{item}} dest=/tmp/{{item}}
    with_items:
      - slurm-{{SLURM_VERSION}}.x86_64.rpm
      - slurm-devel-{{SLURM_VERSION}}.x86_64.rpm
      - slurm-munge-{{SLURM_VERSION}}.x86_64.rpm
      - slurm-openlava-{{SLURM_VERSION}}.x86_64.rpm
      - slurm-pam_slurm-{{SLURM_VERSION}}.x86_64.rpm
      - slurm-perlapi-{{SLURM_VERSION}}.x86_64.rpm
      - slurm-plugins-{{SLURM_VERSION}}.x86_64.rpm
      - slurm-seff-{{SLURM_VERSION}}.x86_64.rpm
      - slurm-sjobexit-{{SLURM_VERSION}}.x86_64.rpm
      - slurm-sjstat-{{SLURM_VERSION}}.x86_64.rpm
      - slurm-slurmdb-direct-{{SLURM_VERSION}}.x86_64.rpm
      - slurm-slurmdbd-{{SLURM_VERSION}}.x86_64.rpm
      - slurm-sql-{{SLURM_VERSION}}.x86_64.rpm
      - slurm-torque-{{SLURM_VERSION}}.x86_64.rpm

  - name: Install rpm slurm packages (common)
    yum:
      name:
        - "/tmp/slurm-{{SLURM_VERSION}}.x86_64.rpm"
        - "/tmp/slurm-devel-{{SLURM_VERSION}}.x86_64.rpm"
        - "/tmp/slurm-munge-{{SLURM_VERSION}}.x86_64.rpm"
        - "/tmp/slurm-openlava-{{SLURM_VERSION}}.x86_64.rpm"
        - "/tmp/slurm-pam_slurm-{{SLURM_VERSION}}.x86_64.rpm"
        - "/tmp/slurm-perlapi-{{SLURM_VERSION}}.x86_64.rpm"
        - "/tmp/slurm-plugins-{{SLURM_VERSION}}.x86_64.rpm"
        - "/tmp/slurm-seff-{{SLURM_VERSION}}.x86_64.rpm"
        - "/tmp/slurm-sjobexit-{{SLURM_VERSION}}.x86_64.rpm"
        - "/tmp/slurm-sjstat-{{SLURM_VERSION}}.x86_64.rpm"
        - "/tmp/slurm-slurmdb-direct-{{SLURM_VERSION}}.x86_64.rpm"
        - "/tmp/slurm-slurmdbd-{{SLURM_VERSION}}.x86_64.rpm"
        - "/tmp/slurm-sql-{{SLURM_VERSION}}.x86_64.rpm"
        - "/tmp/slurm-torque-{{SLURM_VERSION}}.x86_64.rpm"
      state: present

  - name: Set SLURM conf file path as fact
    set_fact:
      SLURM_CONF: "/etc/slurm/slurm.conf"
      SLURM_SERVICE: "slurm"
      SLURM_DAEMON: "slurm"
