---
  - name: copy slurm.conf file from the frontend
    copy: src=/usr/local/etc/slurm.conf dest={{SLURM_CONF}}

  # A patch to solve some strange issue in CentOS 7
  - lineinfile: dest=/etc/slurm/slurm.conf regexp='^SlurmdPidFile=' line='SlurmdPidFile=/var/run/slurmctld.pid'
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7

  - name: start slurmd daemon in Deb systems
    shell: pgrep slurmd || slurmd
    when: ansible_os_family == "Debian"

  - name: start slurmd daemon in RedHat systems
    command: systemctl enable slurm.service
    when: ansible_os_family == "RedHat"

  - command: systemctl start slurm.service
    when: ansible_os_family == "RedHat"
