---
  - name: Remove the entries in /etc/hosts that correspond to the node name
    shell: cat /etc/hosts | sed "/{{slurm_server_name}}/d" > /tmp/newhosts

  - name: Add a new entry in the hosts file with the new IP address
    shell: echo "{{ slurm_server_ip }} {{ slurm_server_name }}" >> /tmp/newhosts

  - name: Set the new /etc/hosts file
    shell: cp /tmp/newhosts /etc/hosts && rm /tmp/newhosts

  - name: Stop firewall in Centos7
    service: name=firewalld state=stopped
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7
    ignore_errors: yes

  - name: Create the slurm.conf file
    template: dest={{ SLURM_CONF }} src=slurm.conf.j2
    notify: reload slurm

  # start SLURM daemon
  - name: Start SLURM daemon
    service: name={{SLURM_SERVICE}} state=started
