---
    # We have to remove the entries in /etc/hosts that correspond to the node name
    - shell: cat /etc/hosts | sed "/{{slurm_server_name}}/d" > /tmp/newhosts  
    # Now we add a new entry with the new IP address
    - shell: echo "{{ slurm_server_ip }} {{ slurm_server_name }}" >> /tmp/newhosts 
    # Let's set the new /etc/hosts file
    - shell: cp /tmp/newhosts /etc/hosts && rm /tmp/newhosts 

    - service: name=firewalld state=stopped
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7
      ignore_errors: yes

    - local_action: wait_for path=/etc/munge/munge.key timeout=600
      when: not munge_key.stat.exists
    - include: sudo_copy.yaml src=/etc/munge/munge.key dest=/etc/munge/munge.key owner=munge group=munge mode="0400"
      when: not munge_key.stat.exists
      notify: restart munge

    - service: name=munge state=started

    - name: Create the slurm.conf file
      template: dest={{ SLURM_CONF }} src=slurm.conf.j2
      notify: reload slurm

    # start SLURM daemon
    - service: name={{SLURM_SERVICE}} state=started

